# Generated by Django 3.2.9 on 2021-11-09 00:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20211109_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('dialogue_user1_key', models.CharField(blank=True, max_length=64, null=True)),
                ('dialogue_user2_key', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('user1_wait_message_number', models.IntegerField(default=0)),
                ('user2_wait_message_number', models.IntegerField(default=0)),
                ('dialogue_type', models.IntegerField(choices=[(1, '常规'), (2, '用于task')], default=1)),
                ('dialogue_info', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('dialogue_info_user1_wait', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('dialogue_info_user2_wait', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('unread_num', models.IntegerField(default=0)),
                ('dialogue_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dialogues', to='user.user')),
                ('dialogue_user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_dialogues', to='user.user')),
            ],
        ),
    ]
