# Generated by Django 3.2.9 on 2021-11-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20211109_0017'),
        ('dialogue', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.IntegerField(choices=[(1, '商品送货'), (2, '外卖或快递')], default=1)),
                ('description', models.TextField(null=True)),
                ('ddl_time', models.DateTimeField(null=True)),
                ('receive_time', models.DateTimeField(null=True)),
                ('price', models.FloatField()),
                ('task_status', models.IntegerField(choices=[(0, '已取消'), (1, '等待取货'), (2, '等待送达'), (3, '等待确认'), (4, '完成'), (6, '有争议')], default=1)),
                ('dialogue_between_re_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_task_re', to='dialogue.dialogue')),
                ('dialogue_between_up_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_task_up', to='dialogue.dialogue')),
                ('receive_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addr_mer_20', to='user.address')),
                ('receive_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receive_task', to='user.user')),
                ('relation_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_task', to='order.transaction')),
                ('sender_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addr_mer_10', to='user.address')),
                ('sender_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_send_task', to='user.user')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_user_upload', to='user.address')),
            ],
        ),
    ]
