# Generated by Django 3.2.9 on 2021-11-08 02:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('money_receiving_QR_code', models.ImageField(max_length=409600, null=True, upload_to=user.models.User.user_directory_path)),
                ('money', models.FloatField(default=0)),
                ('wait_notice', models.IntegerField(default=0)),
                ('header_photo', models.ImageField(max_length=409600, null=True, upload_to=user.models.User.user_directory_path2)),
                ('user_status', models.IntegerField(choices=[(0, '未激活'), (1, '可以购买'), (2, '可以上传商品')], default=0)),
                ('real_name', models.CharField(max_length=64, null=True)),
                ('user_identify', models.IntegerField(choices=[(1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')], null=True)),
                ('self_description', models.CharField(max_length=512, null=True)),
                ('sold_goods_number', models.IntegerField(default=0)),
                ('uploaded_goods_numbers', models.IntegerField(default=0)),
                ('pay_password', models.CharField(blank=True, max_length=256, null=True)),
                ('stars_for_deliver', models.FloatField(default=5)),
                ('stars_for_good', models.FloatField(default=5)),
                ('stars_for_attitude', models.FloatField(default=5)),
                ('comment_number', models.IntegerField(default=0)),
                ('notice_info_unread', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('notice_info', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('favorite_sellers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=128)),
                ('favorite_merchandise', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=128)),
                ('user_transactions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('user_recommend_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='收件人')),
                ('user_addr', models.CharField(max_length=256, verbose_name='收件地址')),
                ('region', models.IntegerField(choices=[(1, '荔园'), (2, '创园'), (3, '慧园'), (4, '欣园'), (5, '学生宿舍'), (6, '湖畔'), (7, '九华精舍'), (8, '教师公寓'), (9, '专家公寓'), (10, '风雨操场'), (11, '润扬体育馆'), (12, '工学院'), (13, '南科大中心'), (14, '第一科研楼'), (15, '第二科研楼'), (16, '第一教学楼'), (17, '第二教学楼'), (18, '台州楼'), (19, '检测中心'), (20, '行政楼'), (21, '琳恩图书馆'), (22, '1号门'), (23, '2号门'), (24, '3号门'), (25, '4号门'), (26, '5号门'), (27, '6号门'), (28, '7号门'), (29, '8号门'), (30, '其他')], default=1)),
                ('addr_type', models.IntegerField(choices=[(1, '收货'), (2, '发货')], default=1)),
                ('relate_number', models.IntegerField(default=0)),
                ('user_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_to_user', to='user.user')),
            ],
        ),
    ]
