# Generated by Django 3.2.9 on 2021-11-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comment_mer', to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_mer', to='user.user'),
        ),
        migrations.AlterField(
            model_name='commenttask',
            name='comment_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comment_task', to='user.user'),
        ),
        migrations.AlterField(
            model_name='commenttask',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_task', to='user.user'),
        ),
    ]
