# Generated by Django 3.2.9 on 2021-11-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_has_header_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_identify',
            field=models.IntegerField(choices=[(0, '系统管理员'), (1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')], null=True),
        ),
    ]
