# Generated by Django 3.2.9 on 2021-11-09 00:21

import commodity.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20211109_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '运动户外'), (2, '生活用品'), (3, '电器'), (4, '数码'), (5, '服装'), (6, '美妆'), (7, '家具'), (8, '玩具')], default=1)),
                ('name_str', models.CharField(choices=[('运动户外', '运动户外'), ('生活用品', '生活用品'), ('电器', '电器'), ('数码', '数码'), ('服装', '服装'), ('美妆', '美妆'), ('家具', '家具'), ('玩具', '玩具')], default='运动户外', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '运动服'), (2, '运动鞋'), (3, '五金用品'), (4, '办公用品'), (5, '办公设备'), (6, '大家电'), (7, '厨房电器'), (8, '生活电器'), (9, '电脑'), (10, '电脑配件'), (11, '智能设备'), (12, '手机'), (13, '相机'), (14, '上衣'), (15, '外套'), (16, '美容护肤'), (17, '彩妆'), (18, '香水'), (19, '家具饰品'), (20, '住宅家具'), (21, '模型'), (22, '手办')], default=1)),
                ('name_str', models.CharField(choices=[('运动服', '运动服'), ('运动鞋', '运动鞋'), ('五金用品', '五金用品'), ('办公用品', '办公用品'), ('办公设备', '办公设备'), ('大家电', '大家电'), ('厨房电器', '厨房电器'), ('生活电器', '生活电器'), ('电脑', '电脑'), ('电脑配件', '电脑配件'), ('智能设备', '智能设备'), ('手机', '手机'), ('相机', '相机'), ('上衣', '上衣'), ('外套', '外套'), ('美容护肤', '美容护肤'), ('彩妆', '彩妆'), ('香水', '香水'), ('家具饰品', '家具饰品'), ('住宅家具', '住宅家具'), ('模型', '模型'), ('手办', '手办')], default='运动服', max_length=256)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_class', to='commodity.classlevel1')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('image1', models.ImageField(max_length=409600, null=True, upload_to=commodity.models.Merchandise.user_directory_path)),
                ('image2', models.ImageField(max_length=409600, null=True, upload_to=commodity.models.Merchandise.user_directory_path)),
                ('image3', models.ImageField(max_length=409600, null=True, upload_to=commodity.models.Merchandise.user_directory_path)),
                ('price', models.FloatField()),
                ('deliver_price', models.FloatField(default=0)),
                ('thumb', models.ImageField(max_length=102400, null=True, upload_to=commodity.models.Merchandise.user_thumb_directory_path)),
                ('fineness', models.IntegerField(choices=[(1, '全新'), (2, '几乎全新'), (3, '轻微使用痕迹'), (4, '明显使用痕迹')], default=1)),
                ('status', models.IntegerField(choices=[(1, '正在售卖'), (2, '正在交易'), (3, '出现问题'), (4, '已经售出')], default=1)),
                ('favourite_number', models.IntegerField(default=0)),
                ('who_favourite', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('class_level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mer_class1', to='commodity.classlevel1')),
                ('class_level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mer_class2', to='commodity.classlevel2')),
                ('sender_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addr_mer_0', to='user.address')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandises', to='user.user')),
            ],
            options={
                'unique_together': {('name', 'upload_user')},
            },
        ),
    ]
