# Generated by Django 3.2.9 on 2021-11-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='allow_face_trade',
            field=models.BooleanField(default=True),
        ),
    ]
