# Generated by Django 3.2.9 on 2021-11-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_merchandise_allow_face_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='browse_number',
            field=models.IntegerField(default=0),
        ),
    ]
