# Generated by Django 3.2.9 on 2021-11-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20211109_0017'),
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '等待付款'), (2, '等待发货'), (3, '等待收货'), (4, '等待评价'), (5, '已送达'), (6, '有争议')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('receive_time', models.DateTimeField(null=True)),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '线上支付'), (3, '虚拟货币')], default=1, null=True, verbose_name='支付方式')),
                ('trade_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付编号')),
                ('transaction_price', models.FloatField(default=0)),
                ('total_price', models.FloatField()),
                ('receiver_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_to_receiver_tr', to='user.address')),
                ('sender_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_to_sender_tr', to='user.address')),
                ('transaction_merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merc_Transactions', to='commodity.merchandise')),
                ('transaction_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_Transactions', to='user.user')),
                ('transaction_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transactions', to='user.user')),
            ],
        ),
    ]
