# Generated by Django 3.2.9 on 2021-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='QR_pay_status',
            field=models.IntegerField(choices=[(1, '初始状态'), (2, '等待卖家确认'), (3, '卖家已经确认')], default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comfirm_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='send_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '等待付款'), (2, '等待发货'), (3, '等待收货'), (4, '等待评价'), (5, '已送达'), (6, '有争议'), (7, '二维码支付等待确认')], default=1),
        ),
    ]
