# Generated by Django 3.2.9 on 2021-11-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_user_identify'),
        ('order', '0002_auto_20211112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (2, '二维码支付'), (3, '虚拟货币')], default=1, null=True, verbose_name='支付方式'),
        ),
        migrations.CreateModel(
            name='TransactionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.CharField(max_length=512)),
                ('problem_upload_date', models.DateTimeField(auto_now_add=True)),
                ('problem_type', models.IntegerField(choices=[(1, '申请退货'), (2, '线下交易冲突'), (3, '二维码未收款'), (4, '恶意未发货'), (5, '卖家问题')])),
                ('superuser_log', models.CharField(blank=True, max_length=1024, null=True)),
                ('handle_date', models.DateTimeField(null=True)),
                ('handle_superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superuser_rela_problem', to='user.user')),
                ('problem_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_rela_problem', to='order.transaction')),
                ('problem_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rela_problem', to='user.user')),
            ],
        ),
    ]
